# plan_reviewer.py
"""
Plan Reviewer node.
Receives the tactical planner's draft plan and performs structured edits in-place:
1. Strips tasks that are illegal in the current phase.
2. Reorders tasks by priority.
3. Appends tasks to satisfy uncovered coverage requirements from kb.coverage.
"""

import json
from dotenv import load_dotenv
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.output_parsers import PydanticOutputParser

from prototype.sub_agents.helper import extract_json_block
from app.utilities import dc_logger
from app.utilities.llm_helper import LLMHelper
from prototype.sub_agents.schemas import ReviewerOutput, MasterState, void_knowledge

logger = dc_logger.LoggerAdap(dc_logger.get_logger(__name__))
load_dotenv()

reviewer_llm = LLMHelper.get_llm_for_service("plan_reviewer")
reviewer_parser = PydanticOutputParser(pydantic_object=ReviewerOutput)

REVIEWER_SYSTEM_PROMPT = """You are the Plan Reviewer for an automated web penetration testing framework.

Your sole job is to review and edit the draft task list generated by the tactical planner for the current phase.
You must return the revised task list using the exact structure specified in the schema output.

CONSTRAINTS — READ CAREFULLY:
1. You may ONLY perform three operations on the task list:
   - DELETE: Remove tasks that are illegal in the active phase, or redundant.
   - APPEND: Append ONLY tasks that directly satisfy uncovered coverage entries in the coverage matrix (from kb.coverage). You are strictly forbidden from inventing new work or types of testing outside of these coverage entries. You MUST explicitly include the target IP, hostname, URL, or link in the task description of any tasks you append.
   - REORDER: Sort tasks by execution priority.
2. You are strictly FORBIDDEN from rewriting or editing any task description, changing task parameters, or swapping tools. If you retain a task, keep its "task_description", "task_id", and "agent" exactly identical to the draft. If a draft task has a description missing its target, you may delete it so the planner regenerates it correctly, but do not edit its description text.
3. Set status to "approved" if no changes were needed, or "edited" if you made deletions, appends, or reordering.

PHASE CONSTRAINTS:
- RECON: ports, services, endpoints, JS, APIs, forms, parameters. Nothing active.
  * NO injection payloads of any kind (no XSS, SQLi, template injection, command injection, path traversal, or parameter fuzzing).
  * NO vulnerability testing or active verification of any kind.
- ATTACK_ANALYSIS: Validate discovered attack surfaces using passive or active techniques as appropriate (XSS, SQLi, IDOR, auth, headers, CVEs, PoCs).
- REPORTING: No agent execution. All tasks must be deleted.

PRIORITY ORDERING RULES:
1. CVE research and exploit intelligence lookups before generic fuzzing.
2. Auth testing and access control testing before deep parameter fuzzing.
3. High-signal/high-priority items before low-signal items.

OUTPUT FORMAT:
""" + reviewer_parser.get_format_instructions()


def _build_user_prompt(state: MasterState) -> str:
    current_phase = state.get("current_phase", "unknown")
    phase_objective = state.get("phase_objective", "")
    knowledge = state.get("knowledge", void_knowledge())
    draft_plan = state.get("plan", [])
    query = state.get("query", "")
    
    # Extract only the coverage matrix and relevant facts from knowledge
    coverage = knowledge.get("coverage", {})
    
    return f"""ORIGINAL OBJECTIVE:
{query}

CURRENT PHASE: {current_phase}
PHASE OBJECTIVE: {phase_objective}

DRAFT PLAN FROM TACTICAL PLANNER:
{json.dumps(draft_plan, indent=2)}

CURRENT COVERAGE STATUS:
{json.dumps(coverage, indent=2)}

Review the draft plan above. Modify it according to the reviewer guidelines:
1. Delete tasks that violate the phase boundaries (e.g. no injection in recon).
2. Append tasks ONLY if they satisfy required coverage items that are not completed. You MUST explicitly include the target IP, hostname, URL, or link in the task description of any tasks you append.
3. Reorder tasks to put CVE checks and high-priority tasks first.
4. Keep all retained task descriptions exactly identical to the draft.
"""


def plan_reviewer(state: MasterState) -> dict:
    """
    Review and edit the tactical planner's draft task list.
    """
    draft_plan = state.get("plan", [])
    if not draft_plan:
        logger.info("[reviewer] Draft plan is empty, skipping review.")
        return {"plan": [], "reviewer_status": "approved", "last_node": "plan_reviewer"}

    messages = [
        SystemMessage(content=REVIEWER_SYSTEM_PROMPT),
        HumanMessage(content=_build_user_prompt(state)),
    ]

    try:
        response = reviewer_llm.invoke(messages)
        reviewed: ReviewerOutput = reviewer_parser.parse(extract_json_block(response.content))
        
        # Enforce description rewrite protection programmatically
        draft_by_id = {t["task_id"]: t for t in draft_plan if "task_id" in t}
        sanitized_tasks = []
        for task in reviewed.task_list:
            task_dict = task.model_dump()
            task_id = task_dict.get("task_id")
            
            # If it was in the original draft, restore its original description/parameters
            if task_id in draft_by_id:
                orig = draft_by_id[task_id]
                task_dict["task_description"] = orig.get("task_description", task_dict["task_description"])
                task_dict["agent"] = orig.get("agent", task_dict["agent"])
                task_dict["depends_on"] = orig.get("depends_on", task_dict["depends_on"])
                task_dict["coverage_keys"] = orig.get("coverage_keys", task_dict.get("coverage_keys", []))
            
            sanitized_tasks.append(task_dict)
            
        metrics = state.get("metrics", {})
        if reviewed.status == "edited":
            metrics["reviewer_edits"] = metrics.get("reviewer_edits", 0) + 1

        logger.info(
            f"[reviewer] Status: {reviewed.status} | "
            f"Original tasks: {len(draft_plan)} -> Final tasks: {len(sanitized_tasks)} | "
            f"Summary: {reviewed.edit_summary}"
        )
        return {
            "plan": sanitized_tasks,
            "reviewer_status": reviewed.status,
            "last_node": "plan_reviewer",
            "metrics": metrics,
        }
        
    except Exception as e:
        logger.error(f"[reviewer] Failed: {e}")
        logger.info(f"Raw response: {response.content if 'response' in locals() else 'N/A'}")
        # On failure, fall back to draft plan to avoid blocking execution
        return {
            "plan": draft_plan,
            "reviewer_status": "approved",
            "last_node": "plan_reviewer"
        }