# plan_reviewer.py
"""
Plan Reviewer node.
Receives the tactical planner's draft plan and performs structured edits in-place:
1. Strips tasks that are illegal in the current phase.
2. Reorders tasks by priority.
3. Appends tasks to satisfy uncovered coverage requirements from kb.coverage.
"""

import json
from dotenv import load_dotenv
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.output_parsers import PydanticOutputParser

from prototype.sub_agents.helper import extract_json_block
from app.utilities import dc_logger
from app.utilities.llm_helper import LLMHelper
from prototype.sub_agents.schemas import ReviewerOutput, MasterState, void_knowledge

logger = dc_logger.LoggerAdap(dc_logger.get_logger(__name__))
load_dotenv()

reviewer_llm = LLMHelper.get_llm_for_service("plan_reviewer")
reviewer_parser = PydanticOutputParser(pydantic_object=ReviewerOutput)

REVIEWER_SYSTEM_PROMPT = """You are the Plan Reviewer for an automated web penetration testing framework.

Your sole job is to review and edit the draft task list generated by the tactical planner.
You must return the revised task list using the exact structure specified in the schema output.

━━━ YOUR ROLE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
You are a REVIEWER, not a planner. The tactical planner will be called again after
execution with updated knowledge. Your job is NOT to schedule all future work upfront.

The tactical planner already demonstrated the correct instinct: plan only what is
executable RIGHT NOW with the knowledge currently available.
Your job is to ENFORCE that discipline, not undo it.

━━━ PERMITTED OPERATIONS (only three) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. DELETE — Remove tasks that:
   - Violate phase boundaries (e.g. injection payloads in recon)
   - Are redundant with already-completed work in the execution history
   - Have unmet prerequisites (see PREREQUISITE GATE below)

2. REORDER — Sort remaining tasks by priority (CVE checks first, then
   high-signal items, then broad enumeration).

3. APPEND — Add a task ONLY if ALL of the following are true:
   a. It satisfies a coverage item that is marked required=True AND completed=False
      in the current coverage matrix.
   b. Its prerequisites are ALREADY SATISFIED in the knowledge graph right now.
      Ask yourself: "Can this task execute immediately with what we know?"
      If the answer is NO, do not append it.
   c. It is not already in the draft plan.
   d. You explicitly include the target IP, hostname, or URL in the task description.

━━━ PREREQUISITE GATE — CHECK THIS BEFORE EVERY APPEND ━━━━━━━━━━━━━━━━━━━━━

Before appending any task, ask:

  "Directory/JS/API/param discovery" → Do I know a confirmed HTTP URL right now?
    NO HTTP URL in knowledge graph → DO NOT APPEND. Wait for nmap to run first.

  "Service fingerprinting" → Do I know any open ports right now?
    NO PORTS in knowledge graph → DO NOT APPEND.

  "XSS/SQLi/IDOR testing" → Am I in a phase that permits testing? Do I have input_points?
    RECON phase OR no input_points → DO NOT APPEND.

  "CVE verification" → Do I have a confirmed CVE in exploit_intelligence?
    NO CVE FOUND YET → DO NOT APPEND.

If you cannot find the prerequisite data in the knowledge graph provided,
the task is speculative. Speculative tasks must be DELETED, never appended.

━━━ WHAT A GOOD CYCLE-1 REVIEW LOOKS LIKE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The tactical planner produces: [nmap scan]
Knowledge graph: empty (no ports, no services, no URLs)
Correct reviewer output: status=approved, task_list=[nmap scan unchanged]
Wrong reviewer output: appended gobuster, JS discovery, param extraction

The planner will be called again after nmap runs. Those tasks will be
scheduled then, once the HTTP service is confirmed. NOT before.

━━━ HARD CONSTRAINTS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

- NEVER rewrite or edit any retained task description, agent, or parameters.
  If a task has an incorrect description, DELETE it (planner will regenerate).
- NEVER invent work outside the coverage matrix.
- NEVER schedule tasks whose prerequisites are not yet satisfied.
- Set status="approved" if no changes were needed, "edited" if you changed anything.

PHASE CONSTRAINTS:
- RECON: Discovery only. NO injection payloads. NO vulnerability testing.
- ATTACK_ANALYSIS: Active testing permitted.
- REPORTING: Delete all tasks.

OUTPUT FORMAT:
""" + reviewer_parser.get_format_instructions()


def _build_user_prompt(state: MasterState) -> str:
    current_phase   = state.get("current_phase", "unknown")
    phase_objective = state.get("phase_objective", "")
    knowledge       = state.get("knowledge", void_knowledge())
    draft_plan      = state.get("plan", [])
    query           = state.get("query", "")

    coverage = knowledge.get("coverage", {})

    # Surface the prerequisite state explicitly so the reviewer can apply the gate
    ports        = knowledge.get("ports", {})
    services     = knowledge.get("services", {})
    endpoints_d  = knowledge.get("endpoints_dict", {})
    inputs_d     = knowledge.get("inputs", {})
    exploit_intel = knowledge.get("exploit_intelligence", {})

    http_urls = [
        v.get("url", f"http://target:{v.get('port',80)}")
        for v in services.values()
        if any(kw in str(v.get("url", "")).lower() or
               kw in str(v.get("port", "")).lower()
               for kw in ("80", "443", "8080", "8443", "http"))
    ] or list(endpoints_d.keys())[:3]

    prereq_state = f"""PREREQUISITE STATE (what is actually known right now):
  open_ports known:       {len(ports)} → {list(ports.keys()) or 'NONE'}
  HTTP services/URLs:     {len(http_urls)} → {http_urls or 'NONE — do not schedule dir/JS/API/param discovery'}
  input_points known:     {len(inputs_d)} → {list(inputs_d.keys())[:3] or 'NONE'}
  CVEs in intel:          {len(exploit_intel)} → {list(exploit_intel.keys()) or 'NONE'}

GATE CHECKS:
  Can run dir/JS/API/param discovery? {'YES — HTTP service confirmed' if http_urls else 'NO — no HTTP service yet'}
  Can run service fingerprinting?     {'YES — ports known' if ports else 'NO — no ports yet'}
  Can run CVE verification?           {'YES — CVEs found' if exploit_intel else 'NO — no CVEs yet'}
  Can run injection testing?          {'YES — attack_analysis phase' if current_phase == 'attack_analysis' else 'NO — wrong phase or missing inputs'}"""

    return f"""ORIGINAL OBJECTIVE:
{query}

CURRENT PHASE: {current_phase}
PHASE OBJECTIVE: {phase_objective}

{prereq_state}

DRAFT PLAN FROM TACTICAL PLANNER:
{json.dumps(draft_plan, indent=2)}

CURRENT COVERAGE STATUS:
{json.dumps(coverage, indent=2)}

Review the draft plan:
1. DELETE tasks that violate phase boundaries or have unmet prerequisites (check GATE CHECKS above).
2. APPEND tasks ONLY if their coverage item is required=True AND completed=False AND the
   prerequisite gate check above says YES for that task type.
3. REORDER to put CVE checks and high-priority tasks first.
4. Keep all retained task descriptions exactly identical to the draft.
"""


def plan_reviewer(state: MasterState) -> dict:
    """
    Review and edit the tactical planner's draft task list.
    """
    draft_plan = state.get("plan", [])
    if not draft_plan:
        logger.info("[reviewer] Draft plan is empty, skipping review.")
        return {"plan": [], "reviewer_status": "approved", "last_node": "plan_reviewer"}

    messages = [
        SystemMessage(content=REVIEWER_SYSTEM_PROMPT),
        HumanMessage(content=_build_user_prompt(state)),
    ]

    try:
        response = reviewer_llm.invoke(messages)
        reviewed: ReviewerOutput = reviewer_parser.parse(extract_json_block(response.content))
        
        # Enforce description rewrite protection programmatically
        draft_by_id = {t["task_id"]: t for t in draft_plan if "task_id" in t}
        sanitized_tasks = []
        for task in reviewed.task_list:
            task_dict = task.model_dump()
            task_id = task_dict.get("task_id")
            
            # If it was in the original draft, restore its original description/parameters
            if task_id in draft_by_id:
                orig = draft_by_id[task_id]
                task_dict["task_description"] = orig.get("task_description", task_dict["task_description"])
                task_dict["agent"] = orig.get("agent", task_dict["agent"])
                task_dict["depends_on"] = orig.get("depends_on", task_dict["depends_on"])
                task_dict["coverage_keys"] = orig.get("coverage_keys", task_dict.get("coverage_keys", []))
            
            sanitized_tasks.append(task_dict)
            
        metrics = state.get("metrics", {})
        if reviewed.status == "edited":
            metrics["reviewer_edits"] = metrics.get("reviewer_edits", 0) + 1

        logger.info(
            f"[reviewer] Status: {reviewed.status} | "
            f"Original tasks: {len(draft_plan)} -> Final tasks: {len(sanitized_tasks)} | "
            f"Summary: {reviewed.edit_summary}"
        )
        return {
            "plan": sanitized_tasks,
            "reviewer_status": reviewed.status,
            "last_node": "plan_reviewer",
            "metrics": metrics,
        }
        
    except Exception as e:
        logger.error(f"[reviewer] Failed: {e}")
        logger.info(f"Raw response: {response.content if 'response' in locals() else 'N/A'}")
        # On failure, fall back to draft plan to avoid blocking execution
        return {
            "plan": draft_plan,
            "reviewer_status": "approved",
            "last_node": "plan_reviewer"
        }